### ISSUE TITLE
Run LaTeX multiple times

### ISSUE THREAD

**Issue by rwestlund** [saadq/node-latex#1]
Most non-trivial LaTeX documents require multiple passes.  For example, anything using section references, table of contents, `longtable`, `lastpage`, etc.

It's difficult to automatically determine how many passes a document needs at compile time.  I think the easiest solution is to have a parameter `options.passes` that determines how many times LaTeX is invoked before the document is returned.

**Comment by saadq** [comment]
Thanks for your issue and sorry for the delay. Admittedly, I am not vastly experienced with LaTeX and this project had originated for a specific need of mine where the LaTeX docs were quite simple so I was not aware that they may require multiple passes. Adding another option sounds like a good idea.

I also see that you have already created pull requests that fixes this issue and #2, so thanks very much for that – it's much appreciated. I should be able to review/merge your changes and have it published as a new minor version on npm by tomorrow. Thanks!

**Comment by rwestlund** [comment]
No problem, thanks for maintaining it.  Some issues are ignored or wait for months, so I appreciate the relatively quick response :)

**Comment by saadq** [comment]
From my tests, everything seems to be working fine with your additions/changes. Thanks and nice work! 👍

**Comment by UrielJavier** [comment]
Sorry, but I have a question. I am a noob. 
How should I pass the string? 
test = "\documentclass{article}\begin{document}Hello World! \end{document}"
latex(test).pipe..?

**Comment by saadq** [comment]
Hey Uriel,

That's essentially the syntax you want to use but I think you'll have an issue with your backslashes. `\documentclass` for example will think you're using the `\` to escape the `d`. You will most likely have to switch out every backslash with 2 backslashes.

For example:

```js
test = "\\documentclass{article}\\begin{document}Hello World! \\end{document}"
latex(test).pipe(...)
```

---

It might also be simpler to just put the regular LaTeX code in a file, read the file contents, and then pass that in.

**file.tex**
```tex
\documentclass{article}
\begin{document}
Hello World! 
\end{document}
```

**app.js**
```js
const { readFile } = require('fs')
const latex = require('latex')

readFile('file.tex', 'utf8', (err, data) => {
  latex(data).pipe(...)
})
```
