### ISSUE TITLE
usage of options

### ISSUE THREAD

**Issue by ZUNJI** [saadq/node-latex#19]
Dear saadq, I find that there exist several options to be loaded, but I cannot find any documentations about the usage of these options (a concrete example like how to set fonts will be great).
Thx!

**Comment by saadq** [comment]
I am currently working on v3 of `node-latex` which is a complete rewrite, and I will hopefully add examples of each option usage in there. For now, here is how you would use some options:

Let's say you had a folder structure like this:

```
.
├── doc.tex
├── fonts
│   ├── lato
│   │   ├── Lato-Bol.ttf
│   │   ├── Lato-BolIta.ttf
│   │   ├── Lato-Reg.ttf
│   │   └── Lato-RegIta.ttf
│   └── raleway
│       ├── Raleway-Bold.otf
│       ├── Raleway-ExtraBold.otf
│       ├── Raleway-ExtraLight.otf
│       ├── Raleway-Heavy.otf
│       ├── Raleway-Light.otf
│       ├── Raleway-Medium.otf
│       ├── Raleway-Regular.otf
│       ├── Raleway-SemiBold.otf
│       └── Raleway-Thin.otf
└── inputs
    └── texstyles.cls
```

To include these fonts when running latex, you just need to include the path to a toplevel directory which they are in. Something like:

```js
const latex = require('node-latex');
const path = require('path');
const fs = require('fs');

const texDocPath = path.join(__dirname, 'doc.tex');
const inputsPath = path.join(__dirname, 'inputs');
const fontsPath = path.join(__dirname, 'fonts');

const input = fs.createReadStream(texDocPath);

const pdf = latex(input, {
  fonts: [fontsPath],  // You can put multiple paths in here if you have fonts in different places
  inputs: [inputsPath] // Same thing for your TEXINPUTS
});

// Do something with pdf...
```

---

If you still have issues with usage, please comment a code example here and I can help you debug. Closing for now though.

**Comment by ZUNJI** [comment]
Thanks for your detailed instruction which is very helpful!

**Comment by EloHailwidis** [comment]
Hello @saadq !
Thanks for your work ;)

I use the options.fonts like you described it, but how can I set the main font in my .tex file ?
I use `\setmainfont` but I get `The fontspec package requires either XeTeX or LuaTeX to function`...
Should I set options.cmd ? I use pdfLatex as default, and I'd like to keep it that way.

Thanks !
(Maybe I should open an other issue instead of commenting on this one. Let me know if you want me to do so and delete this comment.)
