### ISSUE TITLE
Table of contents is empty.

### ISSUE THREAD

**Issue by nshivegowda** [saadq/node-latex#30]
I am trying to create a pdf for a sample tex file. It creates pdf file successfully ,but table of contents is empty. I also observed that files like .toc, .aux does not get created.  Am I missing something?  I have used the simple example from git. 
 function generatePDF( ) {
 const input = fs.createReadStream("new.tex","utf-8");
const output = fs.createWriteStream("output.pdf");
const pdf = latex(input)
 
 pdf.pipe(output)
 pdf.on('error', err => console.error(err))
 pdf.on('finish', () => console.log('PDF generated!'))
}
[new .txt](https://github.com/saadq/node-latex/files/4393186/new.txt)
[output.pdf](https://github.com/saadq/node-latex/files/4393187/output.pdf)

**Comment by saadq** [comment]
Let me preface this by saying that I am actually not that great with LaTeX, and don't know anything about table of contents. 

So with the LaTeX code you provided:

**sample.tex**

```tex
\documentclass{article}
\usepackage{standalone}
\usepackage{tabularx}
\usepackage{float}
\usepackage{multicol}
\usepackage{array}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[dvipsnames,table]{xcolor}
\usepackage{longtable}
\usepackage{hyperref}
\usepackage{caption}

\begin{document}
\tableofcontents
\newpage
\section{First}
First Section.
\section{Second}
Second Section.

\section{Summary}\label{b}
Third Section.
\section{Conclusions}\label{conclusions}
This document is dated to \today.
\end{document}

```

I ran the following in terminal:

```bash
$ pdflatex sample.tex
```

And it resulted in this PDF that had an empty table of contents:

[sample.pdf](https://github.com/saadq/node-latex/files/4398321/sample.pdf)

Which means that the library is kind of working as expected, but I'd like to know a bit more. If this is not the expected result, how do you typically generate your PDF from a LaTeX file? For this example, how would you normally generate a PDF that has a correct table of contents from the TeX sample you provided above?

**Comment by saadq** [comment]
[This answer](https://tex.stackexchange.com/a/301109/78659) explains the issue:

> One of many things one has to learn about LaTeX is that certain operations -- such as the creation of the table of contents and cross-referencing call-outs -- take more than one compilation round to complete fully.

This library already supports using multiple runs by passing a `passes` option to specify how many times you want to run LaTeX.

Here's a minimal example:

```js
const latex = require('node-latex');
const fs = require('fs');

const input = fs.createReadStream('new.tex', 'utf-8');
const output = fs.createWriteStream('output.pdf');

const options = {
  passes: 2
};

const pdf = latex(input, options);

pdf.pipe(output);
pdf.on('error', err => console.error(err));
pdf.on('finish', () => console.log('PDF generated!'));
```

---

Feel free to reopen this if you still see some problems.

**Comment by nshivegowda** [comment]
Sorry for the late response. If I try to generate the pdf manually by running the command pdflatex filename, it creates the pdf, on the first run it creates .aux,.toc and other files and on the next run its creates the pdf with table of contents. I am adding the pdf which was created. 
[new.pdf](https://github.com/saadq/node-latex/files/4414931/new.pdf)

**Comment by saadq** [comment]
Have you tried [my suggestion](https://github.com/saadq/node-latex/issues/30#issuecomment-606979915) with passing a number of `passes` in order to get this to work properly? If you pass in the `passes` property, you should have all the generated files you mentioned, including the table of contents.

**Comment by nshivegowda** [comment]
I tried using "passes", I end up getting the error "Error: You can't process a stream twice. Pass a string to use multiple passes." Since I am reading the tex file as a stream.

**Comment by nshivegowda** [comment]
I found a workaround for this. I used toString() method to convert the tex readstream into string and then used the "passes" option. Now the table of contents appear.  
(I do not want to pass the tex content as a string inside the same file). 
const latex = require('node-latex');
const fs = require('fs');

const input = fs.createReadStream('new.tex', 'utf-8');
   const source= input.toString();
const output = fs.createWriteStream('output.pdf');

const options = {
  passes: 2
};

const pdf = latex(source, options);

pdf.pipe(output);
pdf.on('error', err => console.error(err));
pdf.on('finish', () => console.log('PDF generated!'));

**Comment by saadq** [comment]
Ah sorry, that's correct – if you want to use the `passes` argument, you will need to pass the LaTeX doc as a string instead of a stream. The latex() function accepts either a stream as input or just a regular string so you can either read the file as a string and pass that, or just pass a literal string to it:

```js
const latex = require('node-latex')
const fs = require('fs')

// The `input` can be a regular TeX file or a hardcoded string like below:
const input = `
  \\documentclass{article}
  \\usepackage{standalone}
  \\usepackage{tabularx}
  \\usepackage{float}
  \\usepackage{multicol}
  \\usepackage{array}
  \\usepackage[T1]{fontenc}
  \\usepackage[utf8]{inputenc}
  \\usepackage[dvipsnames,table]{xcolor}
  \\usepackage{longtable}
  \\usepackage{hyperref}
  \\usepackage{caption}

  \\begin{document}
  \\tableofcontents
  \\newpage
  \\section{First}
  First Section.
  \\section{Second}
  Second Section.

  \\section{Summary}\\label{b}
  Third Section.
  \\section{Conclusions}\\label{conclusions}
  This document is dated to \\today.
  \\end{document}
`;

const output = fs.createWriteStream('output.pdf')

const options = {
  passes: 2
}

const pdf = latex(input, options)

pdf.pipe(output)
pdf.on('error', err => console.error(err))
pdf.on('finish', () => console.log('PDF generated!'))
```
