### ISSUE TITLE
Unable to use inside docker container.

### ISSUE THREAD

**Issue by abhikhedekar4241** [saadq/node-latex#36]
I am trying to use the package inside docker container. But since the package needs latex to be installed in the machine, I am getting errors. Can someone help with installing latex on docker container?

**Comment by saadq** [comment]
Hi @abhikhedekar4241, sorry I don't have any experience with Docker so can't help. I think you'll get better visibility if you post your question to StackOverflow or somewhere similar.

Closing this since it's not related to an issue with the library
