### ISSUE TITLE
Error Catch

### ISSUE THREAD

**Issue by urshofer** [saadq/node-latex#7]
Hi –

I needed to write the code like this in order to catch Err on the output pipe:

    var outputPath = "/path/to/pdf.pdf";
    var tex = "\\example string with error";
    const oStream  = fs.createWriteStream(outputPath);
    const lStream  = latex(tex, texsettings);
    lStream.on('error', function(err) {
      console.log(`Error Creating PDF ${err}`)
    })
    lStream.pipe(oStream);
    oStream.on('error', function(err) {
      console.log(`Error Creating PDF ${err}`)
    })

Otherwise, the script crashed with an uncaught error in the pipe.
Maybe worth documenting.
Best,
Urs Hofer

**Comment by saadq** [comment]
Yeah, I tried to keep the example on the README simple but it is probably worth showing error handling. I'll update it in a bit, thanks!

**Comment by saadq** [comment]
Hey @urshofer, very late on this but would you like to add a PR for this?

The current code sample looks like this:

```js
const latex = require('node-latex')
const fs = require('fs')

const input = fs.createReadStream('input.tex')
const output = fs.createWriteStream('output.pdf')

latex(input).pipe(output)
```

It should be updated to something like so:

```js
const latex = require('node-latex')
const fs = require('fs')

const input = fs.createReadStream('input.tex')
const output = fs.createWriteStream('output.pdf')
const pdf = latex(input)

pdf.pipe(output)
pdf.on('error', err => console.error(err))
```
